# Generated by Django 3.2.8 on 2021-10-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.URLField(default='temp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('start_year', models.DateField()),
                ('end_year', models.DateField()),
                ('description', models.ManyToManyField(related_name='experience_bullet', to='core.Bullet')),
            ],
        ),
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.ManyToManyField(related_name='education_bullet', to='core.Bullet'),
        ),
    ]
