# Generated by Django 3.2.8 on 2021-10-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_skill_skill_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='icon',
            field=models.URLField(),
        ),
    ]
