# Generated by Django 3.2.8 on 2021-10-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_interest_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='school',
            new_name='company',
        ),
    ]
